import { Field, ID, InputType } from '@nestjs/graphql';
import { IsPhoneNumber, IsString, Length, MinLength } from 'class-validator';
import {
  INQUIRY_MESSAGE_MAX_LENGTH,
  INQUIRY_NAME_MAX_LENGTH,
} from '@medinstru/config';

@InputType()
export class CreateInquiryInput {
  /**
   * Stable per-SUBMISSION key, generated by the client once and reused on
   * every retry. A lost response is indistinguishable from a failed one, so
   * without this a retry creates a second inquiry.
   */
  @Field()
  @IsString()
  @Length(8, 64)
  idempotencyKey: string;

  @Field(() => ID)
  @IsString()
  productId: string;

  // Length is re-checked against the TRIMMED value in the service: @Length(2)
  // runs against what was submitted, so " A " passes here and would be stored
  // as "A".
  @Field()
  @IsString()
  @Length(2, INQUIRY_NAME_MAX_LENGTH)
  buyerName: string;

  // IsPhoneNumber with no region accepts formatted international numbers; the
  // service canonicalises to E.164 before anything is stored or counted.
  @Field()
  @IsPhoneNumber()
  buyerPhone: string;

  // The upper bound is not cosmetic: this is an unauthenticated endpoint, and
  // an unbounded text field is an amplification vector regardless of what is
  // eventually done with the value.
  @Field()
  @IsString()
  @MinLength(1)
  @Length(1, INQUIRY_MESSAGE_MAX_LENGTH)
  message: string;
}
