import { Field, ID, InputType } from '@nestjs/graphql';
import { IsString, Length } from 'class-validator';
import { Transform } from 'class-transformer';
import { IsE164 } from './is-e164.validator';
import {
  INQUIRY_MESSAGE_MAX_LENGTH,
  INQUIRY_NAME_MAX_LENGTH,
} from '@medinstru/config';

@InputType()
export class CreateInquiryInput {
  /**
   * Stable per-SUBMISSION key, generated by the client once and reused on
   * every retry. A lost response is indistinguishable from a failed one, so
   * without this a retry creates a second inquiry.
   */
  @Field()
  @IsString()
  @Length(8, 64)
  idempotencyKey: string;

  @Field(() => ID)
  @IsString()
  productId: string;

  @Field()
  // TRIMMED BEFORE VALIDATION, and that changes what @Length(2) means.
  // class-validator checks the RAW value, so "  " is two characters and was
  // accepted here -- then rejected by the service, after a Serializable
  // transaction had opened and four rate-limit counts had run. The constraint
  // now enforces what it appears to say.
  //
  // The trimmed value is what flows onward, so the service receives canonical
  // input rather than trimming it a second time.
  @Transform(({ value }: { value: unknown }) =>
    typeof value === 'string' ? value.trim() : value,
  )
  @IsString()
  @Length(2, INQUIRY_NAME_MAX_LENGTH)
  buyerName: string;

  // IsPhoneNumber with no region accepts formatted international numbers; the
  // service canonicalises to E.164 before anything is stored or counted.
  @Field()
  // Asks the SAME function the service does. @IsPhoneNumber() disagreed with
  // normalizeE164 in both directions -- see is-e164.validator.ts for the
  // measured cases, including the +999 range this repo's own seed uses.
  @IsE164()
  buyerPhone: string;

  // The upper bound is not cosmetic: this is an unauthenticated endpoint, and
  // an unbounded text field is an amplification vector regardless of what is
  // eventually done with the value.
  @Field()
  // Same trim, same reason: " " passed @MinLength(1) and reached the service.
  // @MinLength(1) is dropped as redundant -- @Length(1, N) already carries the
  // lower bound, and two constraints saying the same thing invite one of them
  // to be edited alone.
  @Transform(({ value }: { value: unknown }) =>
    typeof value === 'string' ? value.trim() : value,
  )
  @IsString()
  @Length(1, INQUIRY_MESSAGE_MAX_LENGTH)
  message: string;
}
